name: cicd-back-sam

on:
  push:
    branches: [main]
    paths: 'beer-backend/sam/**'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/aws-identity-providers-federation-github-actions
          role-session-name: github-actions-dev
          aws-region: ap-northeast-1

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Sam build
        run: sam build --use-container
        working-directory: ./beer-backend/sam
      
      - name: Sam deploy changeset
        run: sam deploy --config-env default --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: ./beer-backend/sam
